### ISSUE TITLE
binstar --force upload with token gives [BinstarError] Invalid dist_id

### ISSUE THREAD

**Issue by jchodera** [Anaconda-Platform/anaconda-client#173] opened 2015-07-01 00:21 UTC
We have an automated build server that builds conda packages and pushes them to our `omnia/openmm-dev` binstar package, but when passing a token (marked below as `****` for security) and using `--force`, these uploads occasionally fail with `Invalid dist_id` errors. 

```
[vagrant@localhost ~]$ binstar -t **** --quiet upload --force -u omnia --channel main miniconda/conda-bld/*/openmm-dev-*.tar.bz2
Using binstar api site https://api.anaconda.org
[warning] Distribution linux-64/openmm-dev-dev-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
```

This issue has only started to appear recently.

**Comment by srossross** [comment] 2015-07-01 00:44
Thanks for reporting this, I will look into it.

**Comment by jchodera** [comment] 2015-07-04 13:50
Thanks!

**Comment by stephenakearns** [comment] 2015-10-30 22:19
fixed before end of year - part of upcoming epic

**Comment by stephenakearns** [comment] 2015-12-18 21:48
including in new epic - "reenable copy"

**Comment by jchodera** [comment] 2015-12-24 00:40
Thanks for the update, @stephenakearns!

**Comment by j0hn** [comment] 2017-09-28 14:59
Closing this along with #133 because couldn't reproduce. Please file a new ticket if occurs again.

**Closed by j0hn** 2017-09-28 14:59 UTC
Labels: sev:4-low, source:public, type:bug
