### ISSUE TITLE
binstar upload "--force" option not working

### ISSUE THREAD

**Issue by megies** [Anaconda-Platform/anaconda-client#133] opened 2015-03-19 16:13 UTC
On an upload of an already existing file I get a `Distribution already exists. Please use the -i/--interactive or --force options` regardless whether I use the said `--force` option or not.
I think it must have wrong logic in there (the combination of nested if/else/continue return True/False/None is hardly intellegible to me): https://github.com/Binstar/binstar/blob/cd1c1674f7a21d9b200fd2cf11850c55f886b6d8/binstar_client/commands/upload.py#L195-L196

**Comment by megies** [comment] 2015-03-19 16:35
![screenshot from 2015-03-19 17 33 33](https://cloud.githubusercontent.com/assets/1842780/6735414/45d79288-ce5e-11e4-842d-250a320f1a28.png)

**Comment by srossross** [comment] 2015-03-19 17:43
Thanks @megies we are looking into this now.

cc @asmeurer  @LilaHickey

**Comment by j0hn** [comment] 2017-03-06 14:11
I couldn't reproduce this error. Can we confirm that it still exists?

<img width="1431" alt="screen shot 2017-03-06 at 11 08 57 am" src="https://cloud.githubusercontent.com/assets/172606/23613288/98298444-025d-11e7-8d83-ca64709abe45.png">

**Comment by j0hn** [comment] 2017-09-28 14:59
Closing this along with #173 because couldn't reproduce. Please file a new ticket if occurs again.

**Closed by j0hn** 2017-09-28 14:59 UTC
Labels: sev:3-moderate, source:public, type:bug

**Comment by megies** [comment] 2017-09-28 19:45
Would be nice to have the fixing commits link to the reporting issues.. I really can't remember how to reproduce this after two years, so I guess.. thanks for it being supposedly fixed in between ;-)
