### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by pitrou** [Anaconda-Platform/anaconda-client#338] opened 2016-07-12 15:46 UTC
```
> anaconda upload -u numba C:\Miniconda3\conda-bld\win-64\llvmdev-3.8.1-1.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file numba/llvmdev/3.8.1/win-64/llvmdev-3.8.1-1.tar.bz2 ...
[ERROR]
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\binstar_client\commands\upload.py", line 214, in main
    callback=upload_print_callback(args))
  File "C:\Miniconda3\lib\site-packages\binstar_client\__init__.py", line 474, in upload
    self._check_response(res)
  File "C:\Miniconda3\lib\site-packages\binstar_client\__init__.py", line 196, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Unauthorized: ('Authorization header was not given', 401)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\anaconda-script.py", line 5, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "C:\Miniconda3\lib\site-packages\binstar_client\scripts\cli.py", line 87, in main
    description=__doc__, version=version)
  File "C:\Miniconda3\lib\site-packages\binstar_client\scripts\cli.py", line 66, in binstar_main
    return args.main(args)
  File "C:\Miniconda3\lib\site-packages\binstar_client\commands\upload.py", line 219, in main
    except requests_ext.OpenSslError:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by MulticastMatt** [comment] 2016-07-14 18:56
Thanks @pitrou - this is a duplicate of an issue that was previously reported #335...we'll follow up there.

**Closed by MulticastMatt** 2016-07-14 18:56 UTC
